### ISSUE TITLE
参数优化会新建多个数据库实例，leveldb不支持？

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy_leveldb#6]
`plyvel._plyvel.IOError: b'IO error: C:\\Users\\lcxly\\.vntrader\\database.db/LOCK: \xc1\xed\xd2\xbb\xb8\xf6\xb3\xcc\xd0\xf2\xd5\xfd\xd4\xda\xca\xb9\xd3\xc3\xb4\xcb\xce\xc4\xbc\xfe\xa3\xac\xbd\xf8\xb3\xcc\xce\xde\xb7\xa8\xb7\xc3\xce\xca\xa1\xa3\r\n'`

**Comment by vnpy** [comment]
对上述的字符串GBK解码后，信息为：另一个程序正在使用此文件，进程无法访问。

猜测原因可能是LevelDB的文件是以读写双模式打开的，导致同一时间只能有一个进程访问，因此就没法跑多进程优化了。

**Comment by jieyujing** [comment]
所以leveldb对于vnpy很鸡肋啊，参数优化这种io密集型的任务都做不了

vn.py ***@***.***> 于2021年12月31日周五 08:10写道：
